# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'iOSApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for iOSApp
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'

  target 'iOSAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'iOSAppUITests' do
    # Pods for testing
  end

end

target 'watchOSApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for watchOSApp
    pod 'Firebase/Database'
end

target 'watchOSApp WatchKit App' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for watchOSApp WatchKit App
  pod 'Firebase/Database'
end

target 'watchOSApp WatchKit Extension' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for watchOSApp WatchKit Extension
    pod 'Firebase/Database'
end
